name: CI/CD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path: [react-app, express-api]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: cd ${{matrix.path}} && npm install

      - name: Run linter
        run: cd ${{matrix.path}} && npm run lint

  Build:
    needs: Lint

    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Build the Docker images
        run: docker-compose build